name: Generate Congressional District Map

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      district:
        description: 'Congressional District (e.g., KY-06)'
        required: true
        default: 'KY-06'

jobs:
  generate-map:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies for GIS
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gdal-bin \
          libgdal-dev \
          libproj-dev \
          libgeos-dev \
          libspatialindex-dev
    
    - name: Set GDAL environment variables
      run: |
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        echo "CPLUS_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV
        echo "C_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
    
    - name: Verify GIS installation
      run: |
        python -c "import geopandas; print('GeoPandas version:', geopandas.__version__)"
        python -c "import fiona; print('Fiona version:', fiona.__version__)"
        python -c "import shapely; print('Shapely version:', shapely.__version__)"
    
    - name: Determine district to process
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "DISTRICT=${{ github.event.inputs.district }}" >> $GITHUB_ENV
        else
          echo "DISTRICT=KY-06" >> $GITHUB_ENV
        fi
    
    - name: Generate congressional district map
      run: |
        python -m src.core.map_generator --district ${{ env.DISTRICT }} --verbose
    
    - name: Verify output files
      run: |
        echo "=== Generated Files ==="
        find data/ -type f -name "*.geojson" -o -name "*.json" | head -10
        echo "=== Map File ==="
        ls -la index.html || echo "Map file not found"
        echo "=== Directory sizes ==="
        du -sh data/ || echo "Data directory not found"
    
    - name: Upload map artifacts
      uses: actions/upload-artifact@v4
      with:
        name: congressional-map-${{ env.DISTRICT }}
        path: |
          index.html
          data/boundaries/*/boundary.geojson
          data/boundaries/*/boundary_simplified.geojson
          data/boundaries/*/counties.geojson
          data/boundaries/*/county_analysis.json
        retention-days: 30
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: false
        include_cname: false